name: lemon_task
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  go_router: ^14.6.2
  flutter_screenutil: ^5.9.3
  u_credit_card: ^1.4.0
  flutter_multi_formatter: ^2.13.0
  flutter_svg: ^2.0.16

  permission_handler: ^11.3.1
#  flutter_credit_card_scanner: 0.11.9
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  nfc_manager: ^3.5.0
  lottie: ^3.2.0
  ml_card_scanner: ^0.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/svg/
    - assets/lottie/

  fonts:
    - family: Euclid Circular A
      fonts:
        - asset: assets/fonts/euclid_circular_a_bold.ttf
        - asset: assets/fonts/euclid_circular_a_medium.ttf
        - asset: assets/fonts/euclid_circular_a_light.ttf
        - asset: assets/fonts/euclid_circular_a_regular.ttf
        - asset: assets/fonts/euclid_circular_a_semi_bold.ttf
